server.port=${PORT:8081}
spring.application.name=smart-currency

# MySQL Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# Debugging
server.error.include-message=always
server.error.include-stacktrace=always
logging.level.org.springframework.security=DEBUG
