spring.application.name=smart-currency
spring.datasource.url=jdbc:mysql://localhost:3306/smart_currency?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
